### ISSUE TITLE
internal error when canceling a sprout fulfillment pool

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [ManageIQ/integration_tests#3001]
when the test runner is waiting for the fulfillment and one removes the pool, the result is an exception

```
$ py.test fixtures/parallelizer/parallelizer_tester.py --use-sprout --sprout-appliances 2 --sprout-group downstream-56z
Loading templates from trackerbot                                                                                                                                                                                  
no test annotation found in None
Requesting 2 appliances from Sprout at http://$SPROUT/appliances/api
Pool 28134. Waiting for fulfillment ...
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/main.py", line 80, in wrap_session
INTERNALERROR>     config.do_configure()
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/config.py", line 618, in do_configure
INTERNALERROR>     self.hook.pytest_configure(config=self)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 393, in execute
INTERNALERROR>     return wrapped_call(method(*args), self.execute)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 113, in wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 138, in get_result
INTERNALERROR>     py.builtin._reraise(*ex)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 123, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 393, in execute
INTERNALERROR>     return wrapped_call(method(*args), self.execute)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 113, in wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 138, in get_result
INTERNALERROR>     py.builtin._reraise(*ex)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 123, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 393, in execute
INTERNALERROR>     return wrapped_call(method(*args), self.execute)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/.cfme_tests/lib/python2.7/site-packages/_pytest/core.py", line 109, in wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/fixtures/parallelizer/__init__.py", line 114, in pytest_configure
INTERNALERROR>     session = ParallelSession(config)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/fixtures/parallelizer/__init__.py", line 242, in __init__
INTERNALERROR>     pool = self.sprout_client.request_check(self.sprout_pool)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/utils/sprout.py", line 24, in __call__
INTERNALERROR>     return self._client.call_method(self._method_name, *args, **kwargs)
INTERNALERROR>   File "/home/ronny/Projects/RedHatQE/cfme_tests/utils/sprout.py", line 66, in call_method
INTERNALERROR>     result["result"]["class"], result["result"]["message"]))
INTERNALERROR> SproutException: Exception DoesNotExist raised! AppliancePool matching query does not exist.
```

**Comment by psav** [comment]
What would you expect it to do?

**Comment by RonnyPfannschmidt** [comment]
an exit printing the pool is gone, i got this as wip
